<BaseComponentStatusView>:
    size_hint_x: 1
    size_hint_y: 1
    BoxLayout:
        orientation: 'vertical'
        size_hint_x: 1
        size_hint_y: 1
        HSeparator:
            text: ''
            id: name
            size_hint_x: 1
            size_hint_y: 1
        GridLayout:
            id: grid
            padding: [self.height * 0.02, self.height * 0.02]
            row_default_height: root.height * 0.1
            cols: 2
