<SessionNode>:
	orientation: 'horizontal'
	Label:
		id: name
		
<LapNode>:
	orientation: 'horizontal'
	FieldLabel:
		id: lap
		size_hint_x: 0.2
		halign: 'left'
	FieldLabel:
		id: laptime
		size_hint_x: 0.6
	CheckBox:
        id: selected
        size_hint_x: 0.2
		
<SessionBrowser>:
	orientation: 'vertical'
    TreeView:
        size_hint_y: 0.5
        height: dp(300)
        id: sessions
        hide_root: True
        indent_level: -(root.width * 0.1)
	